workflows:
  my-workflow:
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Beta Testers

    scripts:
      - name: Install Expo CLI and eject
        script: | 
          yarn install
          yarn global add expo-cli
          expo eject
      - name: Set Info.plist values
        script: | 
          PLIST=$CM_BUILD_DIR/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Install CocoaPods dependencies
        script: |
            cd ios && pod install

      # ... your other commands

      - name: Build and Archive the iOS app
        script: |
            expo build:ios -t archive
            xcodebuild -workspace ios/YourProjectName.xcworkspace -scheme YourSchemeName -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/MyApp.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Create IPA
        script: |
            xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/MyApp.xcarchive -exportPath $CM_BUILD_DIR/MyApp.ipa -exportOptionsPlist path_to_export_options_plist.plist

      # ... your other commands

      # ... your build commands